name = "T4AQuantics"
uuid = "99202d80-6772-4c79-995b-f2660cf2bd6d"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.6.0"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
T4AITensorCompat = "864b39ca-388c-4f43-a593-a1076cf4b253"
T4APartitionedTT = "7ada5264-53d5-494a-9572-4199565888e0"
T4AQuanticsTCI = "ef09ec98-57a2-49a0-bf0b-86b55a3d9051"
T4ATensorCI = "14428447-6903-48c7-83df-f2cb08af9918"

[compat]
EllipsisNotation = "1"
SparseIR = "^0.96, 0.97, 1"
StaticArrays = "1"
T4APartitionedTT = "0.8"
T4AQuanticsTCI = "0.9"
T4ATensorCI = "0.12"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
T4APartitionedTT = "7ada5264-53d5-494a-9572-4199565888e0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ReTestItems", "Aqua", "T4APartitionedTT", "QuanticsGrids", "SparseIR"]
